module.exports = errorCode => {
  switch (errorCode) {
    case 1: return 'token não informado'
    case 2: return 'token inválido ou não encontrado'
    case 3: return 'XML mal formado ou com erros'
    case 4: return 'Erro de procesamento de XML'
    case 5: return 'API bloqueada ou sem acesso'
    case 6: return 'API bloqueada momentaneamente - muitos acessos no último minuto'
    case 7: return 'Espaço da empresa Esgotado'
    case 8: return 'Empresa Bloqueada'
    case 9: return 'Números de sequencia em duplicidade'
    case 10: return 'Parametro não informado'
    case 20: return 'A Consulta não retornou registros'
    case 21: return 'A Consulta retornou muitos registros'
    case 22: return 'O xml tem mais registros que o permitido por lote de envio'
    case 23: return 'A página que você está tentanto obter não existe'
    case 30: return 'Erro de Duplicidade de Registro'
    case 31: return 'Erros de Validação'
    case 32: return 'Registro não localizado'
    case 33: return 'Registro localizado em duplicidade'
    case 34: return 'Nota Fiscal não autorizada'
    case 99: return 'Sistema em manutenção'
    default: return 'Erro desconhecido'
  }
}